### ISSUE TITLE
[Bug]: Cargo failling to compile v4l-sys

### ISSUE THREAD

**Issue by dxwil** [maximbaz/wluma#103]
### Steps for reproducing the issue

run `make build` on Fedora aarch64

### What is the buggy behavior?

I'm getting the following error code:

[dxwil@asahi wluma]$ make build
cargo build --locked --release
   Compiling v4l-sys v0.3.0
error: failed to run custom build command for 'v4l-sys v0.3.0'

Caused by:
  process didn't exit successfully: '/home/dxwil/Build/wluma/target/release/build/v4l-sys-c55733300b09fa98/build-script-build' (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=v4l1
  cargo:rustc-link-lib=v4l2
  cargo:rustc-link-lib=v4lconvert

  --- stderr
  /usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
  thread 'main' panicked at /home/dxwil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v4l-sys-0.3.0/build.rs:14:10:
  Failed to generate bindings: ClangDiagnostic("/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:15: build] Error 101

### What is the expected behavior?

For it to compile

### Logs

```shell
RUST_LOG=debug wluma
```

### Version

4.0.4

### Environment

```shell
LSB Version:	n/a
Distributor ID:	Fedora
Description:	Fedora Linux Asahi Remix 39 (Thirty Nine)
Release:	39
Codename:	n/a
Linux asahi 6.8.7-402.asahi.fc39.aarch64+16k #1 SMP PREEMPT_DYNAMIC Wed Apr 24 00:11:34 UTC 2024 aarch64 GNU/Linux
bash: pacman: command not found
bash: dpkg: command not found
```

**Comment by maximbaz** [comment]
Hello, it looks like a missing -dev package with necessary headers, but more importantly you should know that asahi doesn't support vulkan yet, nor is there access to light sensor, so there isn't much sense to compile wluma yet (I'm also eagerly awaiting vulkan support to be able to use wluma on my asahi 😜)

**Comment by dxwil** [comment]
Oh I see :). I saw an issue about OpenGL support and Vulkan, but I guess I didn't think twice about only Vulkan support. I know there is an ambient light sensor in the macbook (what macOS uses), but does asahi not have drivers and support for it yet?

**Comment by maximbaz** [comment]
I'd be glad to be wrong, but per my current knowledge there is indeed no driver for it yet

**Comment by maximbaz** [comment]
hah, marcan himself has confirmed this an hour ago: https://www.reddit.com/r/AsahiLinux/s/viG3TAHA7i

**Comment by dxwil** [comment]
Oh that's my reddit post asking that, and I still somehow missed his answer. Well good to know anyways
