### ISSUE TITLE
How do I adjust the brightness

### ISSUE THREAD

**Issue by Visual-Dawg** [maximbaz/wluma#110]
Probably a stupid question, but how do I change the brightness after running wluma?

**Comment by maximbaz** [comment]
Before wluma learned your preference, you can adjust brightness using any other tool, like brightnessctl, light or whatever else you were using before you found wluma! With time, as wluma learns more and more about your preferences, you will hopefully find yourself adjusting brightness using those other tools less and less 🙂

**Comment by Visual-Dawg** [comment]
Great, thank you! :)
