### ISSUE TITLE
[Feature request]: disable screen contents brightness

### ISSUE THREAD

**Issue by cesorious** [maximbaz/wluma#112]
### Please describe your feature request

Would it be possible to add a config option to disable wluma from looking at the screen contents and instead only use the webcam/sensor to update brightness? While the option is nice, it is not something I and perhaps others need, so being able to disable it would be nice.

**Comment by maximbaz** [comment]
Hello! You can set `capturer=none` to achieve the desired effect 🙂

**Comment by cesorious** [comment]
Thank you very much, this is what I needed!
