### ISSUE TITLE
[Feature request]: Keyboard detection

### ISSUE THREAD

**Issue by pasikonik** [maximbaz/wluma#70]
How to detect my keyboard?
I have DELL laptop, but I don't have file:
`/sys/bus/platform/devices/dell-laptop/leds/dell::kbd_backlight`
I don't even `leds` folder in `dell-laptop`

**Comment by maximbaz** [comment]
Try installing [light](https://github.com/haikarainen/light) and running `light -L`, maybe it will give some useful hints?

I think I just found those paths referenced on different websites, I didn't really use any concrete method.

**Comment by pasikonik** [comment]
Nothing that would fit
```
~ ❯ light -L
sysfs/backlight/intel_backlight
sysfs/backlight/auto
sysfs/leds/input4::capslock
sysfs/leds/phy0-led
sysfs/leds/input4::scrolllock
sysfs/leds/input4::numlock
sysfs/leds/mmc0::
util/test/dryrun
```

I found on readme

>  the command will operate on the device called sysfs/backlight/auto, which works as it's own device however it proxies the backlight device that has the highest controller resolution

**Comment by maximbaz** [comment]
Hey, did you manage to find a way to find the way to control your keyboard backlight? I'm also wondering if your device simply doesn't support it, i.e. there's no other app that can change brightness of your keyboard? (and if there is, even a simple `strace` could perhaps help figure out how it works).

I'll close the ticket as it's not actionable for this project, but happy to continue discussion if you have any findings, and also if you find a solution and want to include it in README, feel free to send a PR!
