### ISSUE TITLE
[Bug]: ./Downloads/wluma: error while loading shared libraries: libv4l2.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by newyorkthink** [maximbaz/wluma#77]
### Steps for reproducing the issue

![image](https://github.com/maximbaz/wluma/assets/87791643/0abc6911-4dbd-4406-b77f-16c09def5e4b)

### What is the buggy behavior?

![image](https://github.com/maximbaz/wluma/assets/87791643/41bae0c5-1a99-456e-ad4d-263536b717ad)

### What is the expected behavior?

![image](https://github.com/maximbaz/wluma/assets/87791643/3afa6c7e-b4a5-48af-9301-f32e1151079e)

### Logs

```shell
RUST_LOG=debug wluma
```

### Version

![image](https://github.com/maximbaz/wluma/assets/87791643/5ba64c6b-4cf2-4e53-985d-85c61d80336c)

### Environment

```shell
lsb_release -a; uname -a; pgrep -l sway; pacman -Q | egrep "(wlroots|vulkan|sway|clang|rust)"; dpkg -l | egrep "(wlroots|vulkan|sway|clang|rust)"
```

**Comment by maximbaz** [comment]
Based on your report, looks like the "buggy behavior" already matches the "expected behavior"?

**Comment by cyrinux** [comment]
@newyorkthink You need, in archlinux, the package `v4l-utils` who provide the v4l library to build the project.
```$ pacman -Ql  v4l-utils | grep /usr/lib/libv4l2.so
v4l-utils /usr/lib/libv4l2.so
v4l-utils /usr/lib/libv4l2.so.0
v4l-utils /usr/lib/libv4l2.so.0.0.0
``` 
Install this lib depending the linux distribution you use.

**Comment by maximbaz** [comment]
Thanks, and just to add, the full list of dependencies can also be found in README, in the [Build](https://github.com/maximbaz/wluma#build) section. Will close the ticket as hopefully solved, please feel free to comment if you have more specific questions.
