### ISSUE TITLE
[Bug]: No such file or directory

### ISSUE THREAD

**Issue by newyorkthink** [maximbaz/wluma#78]
### Steps for reproducing the issue

![image](https://github.com/maximbaz/wluma/assets/87791643/f3d6d3e4-883f-48a2-8ab1-0eb297e8554c)

### What is the buggy behavior?

![image](https://github.com/maximbaz/wluma/assets/87791643/1ad55c8f-a604-48e0-865d-de65d7b515ee)

### What is the expected behavior?

![image](https://github.com/maximbaz/wluma/assets/87791643/53cbd099-406e-45fb-8abf-4fb13fa51595)

### Logs

```shell
RUST_LOG=debug wluma
```

### Version

![image](https://github.com/maximbaz/wluma/assets/87791643/f50b772b-dcee-426c-8e56-3640c767f653)

### Environment

```shell
lsb_release -a; uname -a; pgrep -l sway; pacman -Q | egrep "(wlroots|vulkan|sway|clang|rust)"; dpkg -l | egrep "(wlroots|vulkan|sway|clang|rust)"
```

**Comment by maximbaz** [comment]
Please fill out the issue template, I have no idea what you mean

**Comment by cyrinux** [comment]
@newyorkthink you dont have a `iio` device.

Looks like you don't have a light sensors device. So you hace to use the `als` webcam or none mode.

```
[als.webcam]
video = 0
thresholds = { 0 = "night", 15 = "dark", 30 = "dim", 45 = "normal", 60 = "bright", 75 = "outdoors" }

# [als.none]
```

Please try to be more verbose the next time. And fill well the issue according to the template.

**Comment by maximbaz** [comment]
I hope this helped, will close as not-actionable, but do feel free to comment if you have further questions! And thanks @cyrinux for the helpful snippet :wink:
